version: 2
jobs:
  install_ruby_dependencies:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
    working_directory: ~/app
    environment:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-v2-{{ checksum "Gemfile.lock" }}
            - ruby-dependencies-v2
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Bundle Install
          command: |
            bundle check || bundle install --deployment
      - save_cache:
          paths:
            - vendor/bundle
          key: ruby-dependencies-v2-{{ checksum "Gemfile.lock" }}
  install_javascript_dependencies:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - javascript-dependencies-v2-{{ checksum "yarn.lock" }}
            - javascript-dependencies-v2
      - run:
          name: Which yarn?
          command: yarn -v
      - run:
          name: Install Yarn
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: javascript-dependencies-v2-{{ checksum "yarn.lock" }}

  run_tests:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
      - image: postgres:11.0-alpine
    parallelism: 1
    environment:
      DB_PORT: 5432
      RAILS_ENV: test
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-v2-{{ checksum "Gemfile.lock" }}
            - ruby-dependencies-v2
      - restore_cache:
          keys:
            - javascript-dependencies-v2-{{ checksum "yarn.lock" }}
            - javascript-dependencies-v2
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432
      - run:
          name: Setup DB
          command: |
           cp config/database.yml.ci config/database.yml
           bundle exec rails db:create db:schema:load
      - run:
          name: Install Chromedriver latest version
          command: |
            sudo apt-get update
            sudo apt-get install lsb-release libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb
      - run:
          name: Run RuboCop
          command: bundle exec rubocop            
      - run:
          name: Run Rspec
          command: |
            bundle exec rspec --format documentation \
                              --format RspecJunitFormatter \
                              -o /tmp/test-results/rspec.xml \
      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: tmp/capybara

workflows:
  version: 2
  main:
    jobs:
      - install_ruby_dependencies
      - install_javascript_dependencies
      - run_tests:
          requires:
            - install_ruby_dependencies
            - install_javascript_dependencies